name: Pull Request Event

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, closed]

jobs: 
  Setup-Init-CI-Vars:
    uses: ./.github/workflows/setup-init-ci-vars.yml
    secrets: inherit

  Welcome-New-Contributor:
    if: github.event.action == 'opened'
    uses: ./.github/workflows/welcome-new-contributor.yml
    secrets: inherit

  Check-Pull-Request:
    if: ${{ github.event.action != 'synchronize' && github.event.action != 'closed' && github.base_ref == 'main' }}
    uses: ./.github/workflows/check-pr.yml
    secrets: inherit

  Check-Branch:
    if: ${{ github.event.action != 'synchronize' && github.event.action != 'closed' && github.base_ref == 'main' }}
    uses: ./.github/workflows/check-branch.yml
    secrets: inherit

  Build-Lint-Test:
    if: ${{ github.event.action != 'edited' && github.event.action != 'closed' }}
    needs: ['Setup-Init-CI-Vars']
    uses: ./.github/workflows/build-lint-test.yml
    secrets: inherit
    with: 
      TARGET_ENV: ${{ needs.Setup-Init-CI-Vars.outputs.ENV_NAME }}
      TARGET_APP: ${{ needs.Setup-Init-CI-Vars.outputs.APP_NAME }}

  Review-App-Heroku:
    if: ${{ github.event.action != 'edited' && github.event.action != 'closed' }}
    needs: ['Setup-Init-CI-Vars', 'Build-Lint-Test']
    uses: ./.github/workflows/review-app-heroku-node.yml
    secrets: inherit
    with: 
      TARGET_ENV: ${{ needs.Setup-Init-CI-Vars.outputs.ENV_NAME }}
      TARGET_APP: ${{ needs.Setup-Init-CI-Vars.outputs.APP_NAME }}

  Destroy-Review-App-Heroku:
    if: github.event.action == 'closed'
    needs: ['Setup-Init-CI-Vars']
    uses: ./.github/workflows/destroy-review-app-heroku-node.yml
    secrets: inherit
    with: 
      TARGET_ENV: ${{ needs.Setup-Init-CI-Vars.outputs.ENV_NAME }}
      TARGET_APP: ${{ needs.Setup-Init-CI-Vars.outputs.APP_NAME }}

  Assign-Milestone-To-PR:
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true && github.base_ref == 'main' }}
    needs: ['Setup-Init-CI-Vars']
    uses: ./.github/workflows/assign-milestone-to-pr.yml
    secrets: inherit
    with: 
      TARGET_ENV: ${{ needs.Setup-Init-CI-Vars.outputs.ENV_NAME }}
      TARGET_APP: ${{ needs.Setup-Init-CI-Vars.outputs.APP_NAME }}

  Reassign-PRs-To-Milestone:
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == false && github.base_ref == 'production' && github.event.pull_request.milestone != null }}
    needs: ['Setup-Init-CI-Vars']
    uses: ./.github/workflows/reassign-prs-after-close.yml
    secrets: inherit
    with: 
      TARGET_ENV: ${{ needs.Setup-Init-CI-Vars.outputs.ENV_NAME }}
      TARGET_APP: ${{ needs.Setup-Init-CI-Vars.outputs.APP_NAME }}