name: Tag and Release
# Tag and Release the version

on:
  workflow_call:
    inputs:
      TARGET_ENV:
        description: 'What environment are we targeting: staging, production, etc'
        required: true
        type: string
      TARGET_APP:
        description: 'The name of the app instance in heroku (i.e. grid-orchestrator-sandbox, grid-orchestrator-staging, grid-orchestrator)'
        required: true
        type: string
    outputs:
      RELEASE_VERSION:
        description: 'The published version of the project'
        value: ${{ jobs.tag_release_job.outputs.RELEASE_VERSION }}


jobs:
  tag_release_job:
    name: Tag & Release Prod Job
    env:
      GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.outs.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Vars
        run: |
          sudo apt-get install jq
          echo "VERSION_NUMBER=$(jq -r '.version' package.json)" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$(jq -r '.build' package.json)" >> $GITHUB_ENV
        working-directory: ./src

      - name: Set GitHub User
        run: |
          git config --global user.name "System Bot"
          git config --global user.email "${{ secrets.SYSTEM_EMAIL }}"

      - name: Tag & Release
        uses: zendesk/action-create-release@v1
        with:
          tag_name: ${{ env.VERSION_NUMBER }}.${{ env.BUILD_NUMBER }}
          release_name: ${{ env.VERSION_NUMBER }}

      - name: Set Outputs
        id: outs
        run: |
          echo "RELEASE_VERSION=${{ env.VERSION_NUMBER }}" >> $GITHUB_OUTPUT