name: Trigger NPM Package Update
# Trigger projects to update one of thier package versions

on:
  workflow_call:
    inputs:
      TARGET_ENV:
        description: 'What environment are we targeting: staging, production, etc'
        required: true
        type: string
      TARGET_APP:
        description: 'The name of the app instance in heroku (i.e. grid-orchestrator-sandbox, grid-orchestrator-staging, grid-orchestrator)'
        required: true
        type: string
      TARGET_REPO_OWNER:
        description: 'The repository owner usually the github organization or personal github name'
        required: true
        type: string
        default: gridverify
      TARGET_REPO_NAME:
        description: 'The name of the repo in github that we are looking to update the package in'
        required: true
        type: string
      PACKAGE_NAME:
        description: 'The name of the package to update in the target repo'
        required: true
        type: string
      PACKAGE_VERSION:
        description: 'The version to update to, if not present then just update to the latest'
        required: false
        type: string
        default: ''

jobs:

  trigger_package_update_job:
    name: Trigger Package Update Job
    runs-on: ubuntu-latest
    env:
      EVENT_TYPE: trigger-npm-package-update
    steps:
      - name: Trigger Package Update
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_API_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ inputs.TARGET_REPO_OWNER }}/${{ inputs.TARGET_REPO_NAME }}/dispatches \
            -d "{\"event_type\": \"${{ env.EVENT_TYPE }}\", \"client_payload\": {\"package_name\": \"${{ inputs.PACKAGE_NAME }}\", \"package_version\": \"${{ inputs.PACKAGE_VERSION }}\"}}"